### ISSUE TITLE
Hie Hie no mie crashes on server

### ISSUE THREAD

**Issue by AngelSuza** [PixelatedW/mineminenomi#173]
Hello,
When i come near of the water the game crashing but only on my server not in solo and this happens all the time. 
Sorry for my english, and this is the crash report.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/04/20 22:12
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$1(LogicalSidedProvider.java:32) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.WyHelper.placeBlockIfAllowed(WyHelper.java:179) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.WyHelper.placeBlockIfAllowed(WyHelper.java:111) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.WyHelper$3.call(WyHelper.java:605) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.updateBlock(Sphere.java:88) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.access$300(Sphere.java:21) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator$1.call(Sphere.java:50) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generateBlocks(Circle.java:71) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generate(Circle.java:16) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.call(Sphere.java:45) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generateBlocks(Circle.java:63) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generate(Circle.java:13) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.math.Sphere.generateFilled(Sphere.java:18) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.api.WyHelper.createFilledSphere(WyHelper.java:600) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.events.abilities.HiePassiveEvents.onEntityUpdate(HiePassiveEvents.java:34) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_47_HiePassiveEvents_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:173) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:179) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[ForgeOptiFine%201.14.4.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$1(LogicalSidedProvider.java:32)
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
	at xyz.pixelatedw.mineminenomi.api.WyHelper.placeBlockIfAllowed(WyHelper.java:179)
	at xyz.pixelatedw.mineminenomi.api.WyHelper.placeBlockIfAllowed(WyHelper.java:111)
	at xyz.pixelatedw.mineminenomi.api.WyHelper$3.call(WyHelper.java:605)
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.updateBlock(Sphere.java:88)
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.access$300(Sphere.java:21)
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator$1.call(Sphere.java:50)
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generateBlocks(Circle.java:71)
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generate(Circle.java:16)
	at xyz.pixelatedw.mineminenomi.api.math.Sphere$SphereGenerator.call(Sphere.java:45)
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generateBlocks(Circle.java:63)
	at xyz.pixelatedw.mineminenomi.api.math.Circle.generate(Circle.java:13)
	at xyz.pixelatedw.mineminenomi.api.math.Sphere.generateFilled(Sphere.java:18)
	at xyz.pixelatedw.mineminenomi.api.WyHelper.createFilledSphere(WyHelper.java:600)
	at xyz.pixelatedw.mineminenomi.events.abilities.HiePassiveEvents.onEntityUpdate(HiePassiveEvents.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_47_HiePassiveEvents_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:173)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220)

**Comment by Wynd** [comment]
1.14 yes ? and thanks for the crashlog

**Comment by AngelSuza** [comment]
Yes 1.14

**Comment by AngelSuza** [comment]
You have a fix for that ? Because it's my favorite fruit...

**Comment by Wynd** [comment]
Sadly there is no fix on that version...you'll need to wait for the new version which will have it fixed.

**Comment by AngelSuza** [comment]
Ok good luck.

**Comment by FGpisces** [comment]
Cleaning up threads, issue has been fixed.
