### ISSUE TITLE
Crashing when creating new world

### ISSUE THREAD

**Issue by Eron12395** [PixelatedW/mineminenomi#184]
The game crashed whilst ticking entity
Error: java.lang.NoSuchMethodError: net.minecraft.entity.LivingEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2020-07-22 16:21
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.LivingEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at fr.zeamateis.damage_indicator.common.handler.event.CommonEventHandler.onLivingUpdate(CommonEventHandler.java:32) ~[?:0.0.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_28_CommonEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:165) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5585/944586917.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:133) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$396/1604342290.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at fr.zeamateis.damage_indicator.common.handler.event.CommonEventHandler.onLivingUpdate(CommonEventHandler.java:32)
	at net.minecraftforge.eventbus.ASMEventHandler_28_CommonEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:165)
	at net.minecraft.client.world.ClientWorld$$Lambda$5585/944586917.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: mineminenomi:bandit_with_sword (xyz.pixelatedw.mineminenomi.entities.mobs.bandits.BanditWithSwordEntity)
	Entity ID: 396
	Entity Name: Bandit with Sword
	Entity's Exact location: -144.50, 25.00, -21.50
	Entity's Block location: World: (-145,25,-22), Chunk: (at 15,1,10 in -10,-2; contains blocks -160,0,-32 to -145,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:133)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Eronic_Gamer'/302, l='MpServer', x=-251.50, y=63.00, z=-39.50]]
	Chunk stats: Client Chunk Cache: 4489, 458
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-256,63,-31), Chunk: (at 0,3,1 in -16,-2; contains blocks -256,0,-32 to -241,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 25 game time, 25 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$396/1604342290.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 924989336 bytes (882 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		Extra-Weapons-Mod-1.14.4.jar Extra Weapons {extraweapons@1.1.8 DONE}
		Useful-Backpacks-Mod-1.14.4.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		Mine Mine no Mi - 1.14.4 - 0.6.2.1.jar Mine Mine no Mi {mineminenomi@0.6.2 DONE}
		U-Team-Core-1.14.4.jar U Team Core {uteamcore@2.8.2.150 DONE}
		CreeperFix-Mod-1.14.4.jar CreeperFix {creeperfix@1.3 DONE}
		Amas-Damage-Indicator-Mod-1.14.4.jar Ama's Damage Indicator {damage_indicator@0.0.3 DONE}
		MrCrayfishs-Furniture-Mod-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		Tree-Chopper-Mod-1.14.4.jar TreeChoppin {treechoppin@1.1.0 DONE}
		Death-Quotes-Mod-1.14.4.jar DeathQuotes {deathquotes@1.0 DONE}
		jei-1.14.4-6.0.0.29.jar Just Enough Items {jei@6.0.0.29 DONE}
		lycanitesmobs-1.14.4-2.1.4.3.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		FastLeafDecay-Mod-1.14.4.jar FastLeafDecay {fastleafdecay@v17 DONE}
		Xaeros_Minimap_20.16.0.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.16.0 DONE}
		HungerStrike-1.14.4-2.0.2.jar Hunger Strike {hungerstrike@1.14.4-2.0.2 DONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor

**Comment by Wynd** [comment]
This crash is caused by damage indicator not mine mine no mi.

**Comment by Eron12395** [comment]
Ah i see thank you, i well get rid of damage indicator then.
