### ISSUE TITLE
Crashing when placing bounty on wall

### ISSUE THREAD

**Issue by Eron12395** [PixelatedW/mineminenomi#189]
I tried to place my bounty on a wall and it crashed the game, every time i try to log into my world it instantly crashes now.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-07-25 19:14
Description: Rendering Block Entity

java.lang.NumberFormatException: For input string: "2 600"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51] {}
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_51] {}
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_51] {}
	at xyz.pixelatedw.mineminenomi.renderers.blocks.WantedPosterTileEntityRenderer.render(WantedPosterTileEntityRenderer.java:105) ~[?:?] {re:classloading}
	at xyz.pixelatedw.mineminenomi.renderers.blocks.WantedPosterTileEntityRenderer.func_199341_a(WantedPosterTileEntityRenderer.java:31) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_203602_a(TileEntityRendererDispatcher.java:139) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:117) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:601) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.23.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$405/1807207655.call(Unknown Source) [forge-1.14.4-28.2.23.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at xyz.pixelatedw.mineminenomi.renderers.blocks.WantedPosterTileEntityRenderer.render(WantedPosterTileEntityRenderer.java:105)
	at xyz.pixelatedw.mineminenomi.renderers.blocks.WantedPosterTileEntityRenderer.func_199341_a(WantedPosterTileEntityRenderer.java:31)

-- Block Entity Details --
Details:
	Name: mineminenomi:wanted_poster // xyz.pixelatedw.mineminenomi.blocks.tileentities.WantedPosterTileEntity
	Block: Block{mineminenomi:wanted_poster}[facing=west]
	Block location: World: (2876,66,562), Chunk: (at 12,4,2 in 179,35; contains blocks 2864,0,560 to 2879,255,575), Region: (5,1; contains chunks 160,32 to 191,63, blocks 2560,0,512 to 3071,255,1023)
	Block: Block{mineminenomi:wanted_poster}[facing=west]
	Block location: World: (2876,66,562), Chunk: (at 12,4,2 in 179,35; contains blocks 2864,0,560 to 2879,255,575), Region: (5,1; contains chunks 160,32 to 191,63, blocks 2560,0,512 to 3071,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_203602_a(TileEntityRendererDispatcher.java:139)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:117)
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:601)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Eronic_Gamer'/29, l='MpServer', x=2875.13, y=65.00, z=564.23]]
	Chunk stats: Client Chunk Cache: 2209, 194
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (256,87,48), Chunk: (at 0,5,0 in 16,3; contains blocks 256,0,48 to 271,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 298631 game time, 298631 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$405/1807207655.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 604864784 bytes (576 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.23
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.23-client.jar Minecraft {minecraft@1.14.4 DONE}
		Extra-Weapons-Mod-1.14.4.jar Extra Weapons {extraweapons@1.1.8 DONE}
		Useful-Backpacks-Mod-1.14.4.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		mine-mine-no-mi-1.14.4-0.6.2.2.jar Mine Mine no Mi {mineminenomi@0.6.2 DONE}
		U-Team-Core-1.14.4.jar U Team Core {uteamcore@2.8.2.150 DONE}
		CreeperFix-Mod-1.14.4.jar CreeperFix {creeperfix@1.3 DONE}
		MrCrayfishs-Furniture-Mod-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		Tree-Chopper-Mod-1.14.4.jar TreeChoppin {treechoppin@1.1.0 DONE}
		Death-Quotes-Mod-1.14.4.jar DeathQuotes {deathquotes@1.0 DONE}
		jei-1.14.4-6.0.0.29.jar Just Enough Items {jei@6.0.0.29 DONE}
		forge-1.14.4-28.2.23-universal.jar Forge {forge@28.2.23 DONE}
		FastLeafDecay-Mod-1.14.4.jar FastLeafDecay {fastleafdecay@v17 DONE}
		Xaeros_Minimap_20.16.0.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.16.0 DONE}
		HungerStrike-1.14.4-2.0.2.jar Hunger Strike {hungerstrike@1.14.4-2.0.2 DONE}
	Launched Version: 1.14.4-forge-28.2.23
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor

**Comment by Wynd** [comment]
Fixed in 0.6.2.3
